matter-labs/zksync-sso-clave-contracts

package.json
src/test/ExampleAuthServerPaymaster.sol

Allow to revoke session via paymaster

fix: allow revoke keys via paymaster

---

.github/workflows/ci.yml

@dutterbutter
The old action is now broken with a rename of the underlying executable
Would like to use older code, but migth have to update other things to get them working

chore: update to renamed action

---

src/validators/SessionKeyValidator.sol

Fix the e2e tests in `zksync-sso` by only allowing to create a session after both the Hook and Module have been initalized

fix: multi validator account creation

---

src/helpers/TimestampAsserterLocator.sol

Add Sepolia `TimestampAsserter` address. Here's the contract in block explorer: https://sepolia.explorer.zksync.io/address/0xa64EC71Ee812ac62923c85cf0796aA58573c4Cf3#contract
Here's also the validation that it's deployed to the Sepolia API server:
```sh
curl --request POST \
--url https://sepolia.era.zksync.dev/ \
--header 'Content-Type: application/json' \
--data '{
"jsonrpc": "2.0",
"id": 1,
"method": "zks_getTimestampAsserter",
"params": []
}'
```
Response:
```sh
{"jsonrpc":"2.0","result":"0xa64ec71ee812ac62923c85cf0796aa58573c4cf3","id":1}
```

chore: add sepolia timestamp asserter address

---

scripts/deploy.ts
src/AAFactory.sol
src/SsoBeacon.sol
test/SessionKeyTest.ts
test/utils.ts

Previously, `TransparentProxy` did not work with `AAFactory` due to it also being an `UpgradeableBeacon` which 
- set the owner and impl in the factory constructor, so proxy did not have those in storage
- had a bunch of overlapping methods between `TransparentProxy` and `UpgradeableBeacon`
This PR splits `AAFactory` and `UpgradeableBeacon` into 2 separate contracts

fix: make factory proxy work

---

src/AAFactory.sol
test/BasicTest.ts
test/utils.ts

Create2 is very specific about what it uses to hash, so getting those exactly from the factory makes doing counterfactual deployments so much easier!
Making the factory deploy using create2 in the tests also helps with run-to-run address comparisons, as it's how everything else is deployed in the tests!
There are like 3 tricks to getting this correct that's worth the test cases to show where the data comes from and how to format it in the same way that solidity does.
1. Now that we have 2 proxies involved in account deployment, picking the correct contract that's getting deployed can be tricky! (AccountProxy is getting deployed, while SsoBeacon is what's getting provided to that proxy)
2. Now that the factory has a proxy, we also need to make sure we're picking that address correctly …

Create2 helpers and example tests

---

scripts/upgrade.ts

Updates to the `upgrade.ts` script to work with `AAFactory.sol` updates.
Example usage:
```sh
pnpm run upgrade AAFactory --beacon-address 0x7719F498DD5E12577d7C8e741d5873FfC5A12CFc --proxy 0x73CFa70318FD25F2166d47Af9d93Cf72eED48724 --network zkSyncSepoliaTestnet
```
```logs
> zksync-sso-contracts@ upgrade /Users/nick/github/matter-labs/zksync-sso-clave-contracts
> pnpm hardhat upgrade "AAFactory" "--beacon-address" "0x7719F498DD5E12577d7C8e741d5873FfC5A12CFc" "--proxy" "0x73CFa70318FD25F2166d47Af9d93Cf72eED48724" "--network" "zkSyncSepoliaTestnet"
Deploying new implementation of AAFactory contract...
Factory doesn't exist at 0x95005e68E2a1dF01Cc1178f50891D636152122A0!
Requesting contract verification...
src/AAFactory.sol:AAFactory
[WARNING] Since Etherscan is disabled or the API key is …
```

fix: update the upgrade scripts to work with AAFactory

---

test/SessionKeyTest.ts

This goes through a slightly different path, it's not specifically interesting, but it's a good example on how to encode the data for session lib session spec
Was pretty convinced this was broken because the extension didn't work, but this turned out to work at least in isolation.

feat: add session on factory creation

---

src/SsoAccount.sol
src/auth/BootloaderAuth.sol
src/auth/HookAuth.sol
src/auth/SelfAuth.sol
src/batch/BatchCaller.sol
src/libraries/Errors.sol
src/libraries/LinkedList.sol
src/managers/HookManager.sol
src/managers/ValidatorManager.sol

Pass values to make debugging easier for that that can decode these errors (hopefully us in the future with better tooling)
also make formatting consistent
Shouldn't have any functional impact, although it does show how many errors the linked list can have

feat: add values to error messages

---

src/helpers/Logger.sol
src/libraries/JsmnSolLib.sol
src/validators/WebAuthValidator.sol

Easy to be explicit and consistent
Audit noted this

feat: int cleanup

---

src/SsoAccount.sol
src/handlers/ERC1271Handler.sol
src/libraries/JsmnSolLib.sol
src/managers/ValidatorManager.sol
src/validators/SessionKeyValidator.sol

If you are using exact matching text searching instead of an IDE, this can make navigating the codebase more clear
Audit feedback

chore: update variable names

---

src/libraries/SessionLib.sol

The check for if the transaction is using a paymaster was incorrect. It checked for the opposite.
Will add fee-limit check tests (including ones using a paymaster) in a follow-up PR

fix: paymaster check in validateFeeLimit

---

src/handlers/ERC1271Handler.sol

`isValidSignature` now accepts k1Owner's ECDSA signatures
As per audit issue

fix: isValidSignature

---

src/handlers/ValidationHandler.sol
src/interfaces/IInitable.sol
src/libraries/JsmnSolLib.sol
src/managers/HookManager.sol
src/managers/OwnerManager.sol
src/test/ExampleAuthServerPaymaster.sol
src/validators/SessionKeyValidator.sol

More deleting dead code
The _delegate call in the proxy appears unused, but there's likely just some extra work to make that more usable instead of removing it.

chore: remove more unused code

---

src/validators/SessionKeyValidator.sol
src/validators/WebAuthValidator.sol

The caller is specified to check the invalid interface id instead of the supports interface function.
Also remove some unused variable names

chore: update duplicate ierc165 check

---

src/SsoAccount.sol
src/libraries/SessionLib.sol
src/validators/SessionKeyValidator.sol

- check session expiration timestamp
- check transaction.to address overflow
- validate contract deployer method selector

fix: better validations

---

src/validators/WebAuthValidator.sol
test/PasskeyModule.ts

More transaction flow test to show integrated usage
Can now compare account signing costs from tests

Passkey Account Test

---

cspell-config/cspell-misc.txt
src/SsoBeacon.sol
src/helpers/TimestampAsserterLocator.sol
src/helpers/TokenCallbackHandler.sol
src/interfaces/IHook.sol
src/interfaces/IModule.sol
src/interfaces/IModuleValidator.sol
src/interfaces/ITimestampAsserter.sol
src/libraries/Errors.sol
src/libraries/SessionLib.sol
src/managers/ValidatorManager.sol
src/validators/SessionKeyValidator.sol
src/validators/WebAuthValidator.sol
test/PasskeyModule.ts

Add doc comments, clean up unused errors and interface methods

docs: add nat-spec doc comments

---

src/interfaces/IHook.sol
src/managers/HookManager.sol
src/managers/OwnerManager.sol
src/managers/ValidatorManager.sol
src/test/TestExecutionHook.sol
src/test/TestValidationHook.sol
test/HooksTest.ts
test/PasskeyModule.ts

- Basic hook tests
- Added back context passing for execution hooks
- Fixed running phantom post-execution hook after hook removal
- Added checks for existing hooks & not found hooks for install & uninstall

test: hook tests

---

src/interfaces/IModule.sol

The IModule.sol file is lacking an SPDX license identifier.
To avoid legal issues regarding copyright and follow best practices, consider adding SPDX license identifiers to files as suggested by the Solidity documentation.
From N-05

chore: add SPDX to IModule.sol

---

src/AAFactory.sol
src/interfaces/IGuardianRecoveryValidator.sol
src/validators/GuardianRecoveryValidator.sol
test/GuardianRecoveryValidatorTest.ts
test/SessionKeyTest.ts
test/utils.ts

- Add a relation between passkey and account.
- Add necessary logic to prevent overlap between recovered and new accounts.
This is necessary in order to validate if an entered passkey is not ready yet but is valid.

feat: add passkey to account relation

---

src/validators/GuardianRecoveryValidator.sol

feat: add guardian added time to guardian information

---

.github/workflows/slither.yml
slither.config.json
src/AAFactory.sol
src/SsoAccount.sol
src/managers/HookManager.sol
src/managers/ValidatorManager.sol

Addition of the Slither static analyzer to the pipeline of the repo. Highlights of the current configuration:
- Runs on PRs.
- Only checks for medium or high-risk findings.
- There is onesilenced detectors ["uninitialized local variables"](https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables).
- It uses `foundry` for compilation instead of `pnpm`, creating the `foundry.toml` file as part of the GH action.
- I have tried compiling it through our recommended steps and then running slither afterward, but it always ends up erroring... Ideally, this should replicate the exact tool chain we used so this remains as a TODO
In addition, some contracts were slightly modified to fully comply with the findings or to silence the unnecessary ones.

feat: Slither pipeline integration

---

src/managers/HookManager.sol

- lock order of pre- and post- exec hooks within a transaction
- don't execute hooks which have been removed and/or added in current transaction

fix: exec hooks behaviour when adding/removing

---

test/PasskeyModule.ts

Adds padding to hex values so that they do not fail to be abi encoded into `bytes32`

test: fix flaky passkey tests

---

src/test/TestWebAuthValidator.sol
src/validators/WebAuthValidator.sol
test/PasskeyModule.ts

Explain the reasoning behind the different validation steps
Hide the function for testing from the published contract and use a test contract to expose it
Audit feedback

chore: add more comments to webauthn verify

---

src/AAFactory.sol
test/BasicTest.ts

This should still allow a single deployer to create predictable
deployment addresses for accounts without allowing front-running
from other addresses!
Suggested by audit, a surprisingly a great suggestion!

feat: change salt depending on deployer

---

src/validators/OidcRecoveryValidator.sol

We were sending the iss hash used to recover the oidc key. That is not needed because the iss is already stored in the contract.

feat: using stored iss to calculate iss hash

---

README.md
scripts/deploy.ts
scripts/upgrade.ts
test/utils.ts

Update upgrade script to perform full deploy and use the file format from the deploy to maintain the proxy addresses.
Because we have to add proxy addresses to an allow list, updating the proxy breaks old accounts. Ideally we never do a fresh deploy again!

feat: perform deploy as part of upgrade

---

src/OidcKeyRegistry.sol
src/validators/OidcRecoveryValidator.sol

https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-01

N-01 Using uint8 for Constants Is More Expensive Than uint256

---

src/OidcKeyRegistry.sol
src/interfaces/IOidcRecoveryValidator.sol
src/validators/OidcRecoveryValidator.sol

https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-06
This is also related to:
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-05
Even when it's not the ideal flow, users can cancel the recovery by letting it expire (which is just 10 minutes).

L-06 Delayed Recovery Validation May Compromise Account Security

---

src/validators/OidcRecoveryValidator.sol
test/OidcKeyRegistryTest.ts
test/OidcRecoveryValidatorTest.ts

I was not able to reproduce this issue. I believe that it was fixed in one of the other PRs, the one about intuitive ordering for circular buffer. Still, I added more tests to ensure that works as expected.
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/M-01

M-01 Incorrect Key Ordering in _compactKeys Function Leads to Potential Overwriting of New Keys

---

src/validators/OidcRecoveryValidator.sol

https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/M-03
We went for a different approach here. Instead of adding a new public input in the circuit we kept re using the content of the nonce. We added the target address and the passkey hash to the data included in the jwt nonce. This links all the information together, making the proof totally linked to one specific recovery

M-03 Unauthorized Control via Manipulated pendingPasskeyHash in startRecovery Process

---

src/validators/AllowedSessionsValidator.sol
test/AllowedSessionsValidatorTest.ts
test/SessionKeyTest.ts
test/utils.ts

This pull request introduces comprehensive tests for the `AllowedSessionsValidator` module and updates utility functions to support the new contract. Key changes include the addition of test cases for session validation logic and the integration of `AllowedSessionsValidator` into the contract fixtures.
* [`test/AllowedSessionsValidatorTest.ts`](diffhunk://#diff-eac4247239334a435376cab63e1d57d9213329e62e2747db92f7acca994aa1b8R1-R337): Added detailed test cases to validate session actions, including hash generation (both on-chain and off-chain), allowing/disallowing session actions, and handling multiple policies. Tests also cover edge cases like rejecting sessions not explicitly allowed and invalidating previously valid sessions.
* `test/utils.ts`: 
- Added `AllowedSessionsValidator` and …

[feat] Tests for AllowedSessionsValidator

---

scripts/deploy.ts

Would not have worked on sepolia before, as it only had a local rich
wallet configured as an owner.
Because this address will be in a live service we don't want to use the
same address as the deployer
some of the final steps to getting this live

feat: add more options to deploy oidc reg

---

scripts/deploy.ts
scripts/publish.ts
scripts/upgrade.ts

Missing update from change
```sh
pnpm run upgrade --proxyfile ../auth-server/stores/era-sepolia.json --keyregistryowner 0x0lol --network zkSyncSepoliaTestnet
> zksync-sso-contracts@ upgrade zksync-sso/packages/contracts
> hardhat upgrade "--proxyfile" "../auth-server/stores/era-sepolia.json" "--keyregistryowner" "0x0lol" "--network" "zkSyncSepoliaTestnet"
Deploying new implementation of undefined contract...
Deploying to: zkSyncSepoliaTestnet
Using custom key registry owner
Deploying WebAuthValidator contract...
Contract WebAuthValidator already exists!
WebAuthValidator contract deployed at: 0x98083a10aa0dC1539267A2e00a7a367D15a21aA3 
Deploying SessionKeyValidator contract...
Contract SessionKeyValidator already exists!
SessionKeyValidator contract deployed at: …
```

fix: update upgrade with new oidc deploy
