- src/validators/SessionKeyValidator.sol
Reverts matter-labs/zksync-sso-clave-contracts#217
> Revert "fix: multi validator account creation"

- src/SsoAccount.sol
- src/interfaces/ISsoAccount.sol
- src/libraries/JsmnSolLib.sol
- src/libraries/SessionLib.sol
- src/managers/ValidatorManager.sol
- src/validators/SessionKeyValidator.sol
- src/validators/WebAuthValidator.sol
- make periods not overlap
- add doc comment
- remove `FeePaid` event
- gas optimizations
> fix: minor issues

- src/AAFactory.sol
- src/SsoAccount.sol
- src/test/ExampleAuthServerPaymaster.sol
- src/test/TestPaymaster.sol
Update imports, very low risk accomplished with autocomplete.
Also updated some implicit imports
N-03
> chore: move imports to different packages

- src/AAFactory.sol
> Feat: fix bug with registering account id when starting recovery process

- src/SsoAccount.sol
- src/interfaces/IHookManager.sol
- src/interfaces/IOwnerManager.sol
- src/interfaces/ISsoAccount.sol
- src/libraries/SessionLib.sol
- src/libraries/SsoStorage.sol
- src/managers/HookManager.sol
- src/managers/OwnerManager.sol
- src/managers/ValidatorManager.sol
Issue fixing of the initial audit results shared last week:
M-01: still in discussion @ly0va
L-01: proposed fix in this PR
L-02: proposed fix in this PR
N-01: proposed fix in this PR
N-02: proposed fix in this PR
N-03: already fixed in [PR267](https://github.com/matter-labs/zksync-sso-clave-contracts/pull/267)
N-04: proposed fix in this PR
N-05: already fixed in [PR262](https://github.com/matter-labs/zksync-sso-clave-contracts/pull/262)
Re-worked [PR266](https://github.com/matter-labs/zksync-sso-clave-contracts/pull/266) to avoid using an external fork and dealing with unsigned commits.
> Fixes of the early results from the second OZ audit

- src/interfaces/IHook.sol
- src/managers/HookManager.sol
Add Matter Labs as contributing authors to file that only mentioned clave
As requested by audit
> chore: update authors on contracts

- src/AAFactory.sol
- src/interfaces/IOwnerManager.sol
- src/managers/HookManager.sol
- src/managers/OwnerManager.sol
Update comments to match the code directly connected to them
As requested by audit
> chore: make comments more exact when referring to internal data

- scripts/deploy.ts
remove redeployed oidc validator
> fix: remove redeployed oidc validator

- scripts/deploy.ts
- src/validators/GuardianRecoveryValidator.sol
- test/utils.ts
> feat: make recoveries origin scoped

- src/validators/OidcRecoveryValidator.sol
- test/OidcKeyRegistryTest.ts
Created method to get an SSO account from a given oidc_digest
Added restriction about no repeated oidc_digest
> feat: added method to get address from oidc_digest

- src/test/ExampleAuthServerPaymaster.sol
- src/validators/GuardianRecoveryValidator.sol
> feat: add small improvements

- src/validators/GuardianRecoveryValidator.sol
> feat: use enumerable set for storing account guardians

- src/OidcKeyRegistry.sol
- test/OidcKeyRegistryTest.ts
> feat: add deleteKey function

- src/OidcKeyRegistry.sol
- test/OidcKeyRegistryTest.ts
> feat: add KeyAdded event

- src/SsoAccount.sol
- src/libraries/SsoStorage.sol
- src/managers/HookManager.sol
- src/managers/ValidatorManager.sol
- src/validators/WebAuthValidator.sol
> fix: minor audit fixes

- src/test/ExampleAuthServerPaymaster.sol
- src/validators/OidcRecoveryValidator.sol
- test/OidcRecoveryValidatorTest.ts
> feat: update addOidcAccount function

- src/OidcKeyRegistry.sol
- test/OidcKeyRegistryTest.ts
> feat: OidcKeyRegistry contract misc improvements

- src/validators/OidcRecoveryValidator.sol
Added `addedOn` for newly added oidc accounts.
> feat: save addedOn for oidc accounts

- src/handlers/ERC1271Handler.sol
> OIDC audit readiness

- src/SsoAccount.sol
- src/libraries/SsoStorage.sol
- src/managers/HookManager.sol
- src/managers/ValidatorManager.sol
- src/validators/WebAuthValidator.sol
N-18 Typographical Error
might have confused some automated comment parsing?
> chore: update comment to remove closing paren

- src/SsoAccount.sol
> Audit (N-02): unused SSO var

- src/validators/WebAuthValidator.sol
> Audit (N-013): minor gas optimization

- src/interfaces/IGuardianRecoveryValidator.sol
- src/test/ExampleAuthServerPaymaster.sol
- src/validators/GuardianRecoveryValidator.sol
- test/GuardianRecoveryValidatorTest.ts
> Audit (N-09): use guardian related names instead of validationKey

- src/validators/GuardianRecoveryValidator.sol
> Audit (N-02): remove unused code (errors)

- src/validators/GuardianRecoveryValidator.sol
> Audit (L-03): pendingRecoveryData does not need to be public

- src/validators/GuardianRecoveryValidator.sol
> Audit (N-12): add security contact

- src/validators/GuardianRecoveryValidator.sol
> Audit (N-15): use more limiting visibility specifier

- src/validators/GuardianRecoveryValidator.sol
> Audit (N-13): use prefix increment operator for gas optimization

- src/validators/OidcRecoveryValidator.sol
> fix: using correct definition for oidc digest in comments

- hardhat.config.ts
Upgrading to the latest zksolc for performance improvements
Last planned change before contract publish (blocks https://github.com/matter-labs/zksync-sso/pull/123)
> feat: upgrade zksolc

- package.json
- test/GuardianRecoveryValidatorTest.ts
- test/PasskeyModule.ts
It looks like only the guardian tests were running
New version of hardhat available
> fix: enable tests

- src/OidcKeyRegistry.sol
- src/validators/OidcRecoveryValidator.sol
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-02
> N-02 Inconsistent License in OidcKeyRegistry.sol

- src/OidcKeyRegistry.sol
- src/validators/OidcRecoveryValidator.sol
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-03
> N-03 Redundant Local Variable in _validateModulus

- src/OidcKeyRegistry.sol
- src/validators/OidcRecoveryValidator.sol
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-04
> N-04 Use of uint Instead of uint256

- src/OidcKeyRegistry.sol
- src/validators/OidcRecoveryValidator.sol
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-05
> N-05 Magic Numbers in the Code

- src/OidcKeyRegistry.sol
- src/validators/OidcRecoveryValidator.sol
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-06
> N-06 Use Custom Errors

- src/OidcKeyRegistry.sol
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-04
> L-04 Potential Loss of Ownership During Transfer

- src/OidcKeyRegistry.sol
- src/interfaces/IOidcRecoveryValidator.sol
- src/validators/OidcRecoveryValidator.sol
- test/OidcRecoveryValidatorTest.ts
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-07
> L-07 Old digestIndex Not Released on OIDC Account Update

- src/OidcKeyRegistry.sol
- src/interfaces/IOidcRecoveryValidator.sol
- src/validators/OidcRecoveryValidator.sol
- test/OidcRecoveryValidatorTest.ts
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-10
> L-10 Insufficient Validation in Recovery Process May Lead to Wasted Recovery Attempts

- src/validators/OidcRecoveryValidator.sol
- test/OidcRecoveryValidatorTest.ts
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-12
> L-12 OidcRecoveryValidator Does Not Follow the ERC-1271 Flow

- src/OidcKeyRegistry.sol
- test/OidcKeyRegistryTest.ts
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-09
> N-09 Circular Buffer Initialization Causes Counterintuitive Key Indexing

- src/OidcKeyRegistry.sol
- src/interfaces/IOidcRecoveryValidator.sol
- src/validators/OidcRecoveryValidator.sol
- test/OidcKeyRegistryTest.ts
- test/OidcRecoveryValidatorTest.ts
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/L-11
> L-11 Insufficient Validation of iss Argument Length in addOidcAccount

- src/validators/OidcRecoveryValidator.sol
- test/OidcKeyRegistryTest.ts
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-16
> N-15 improve comments regarding OIDC pubkeys

- src/OidcKeyRegistry.sol
- src/interfaces/IOidcKeyRegistry.sol
- src/interfaces/IOidcRecoveryValidator.sol
- src/validators/OidcRecoveryValidator.sol
- test/OidcKeyRegistryTest.ts
- test/OidcRecoveryValidatorTest.ts
This changes are on pair with the changes here: https://github.com/Moonsong-Labs/zksync-social-login-circuit/pull/31
https://defender.openzeppelin.com/#/audit/2b38545d-5f25-4e91-9ff8-e465300a0503/issues/N-15
> N-14 Endianness Mismatch in senderHash Representation Between Contract and Circuit

- scripts/publish.ts
Adds SSO account and Guardian module to publish script
This makes setting up from scratch or making abi changes easier
See linked PR: https://github.com/matter-labs/zksync-sso/pull/129
> feat: add guardian contracts to publish

- src/handlers/ERC1271Handler.sol
- src/interfaces/ISsoAccount.sol
- test/BasicTest.ts
- test/PasskeyModule.ts
During merging of OIDC branch the ERC7739 changes were accidentaly reverted as a result of bad conflict resolution, this PR re-adds them
> feat: ERC7739

- src/validators/SessionKeyValidator.sol
Makes `SessionKeyValidator` contract inheritable with overridable methods
> feat: virtualize session key validator methods

- src/libraries/Errors.sol
- src/validators/AllowedSessionsValidator.sol
- src/validators/SessionKeyValidator.sol
> feat: xsolla's AllowedSessionsValidator
